### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by Abdelrahman-Alkhodary** [DeepanChakravarthiPadmanabhan/KeypointNet#1]
Hello 
I'm trying to implement keypointnet in my project. I generated my custom dataset and i'm using your code reimplementation of keypointnet with tensorflow 2.0. I have trained the network on my custom dataset and I would like to confirm it was trained well, so i'm using the prediction code you provided but there was something odd in the code in the function that draws points on the images specifically in that line  
x = (min(max(x, -1), 1) * vw / 2 + vw / 2) - 0.5
if the is negative the output will always be 63, if positive it will be 64, so can you provide me with a solution to this.

also this  is an output of the uvz of the model
[[-9.5309224e-07 -4.7613867e-07 -5.1632648e+02]
 [-9.5309224e-07  4.6566129e-10  4.4604336e+03]
 [-2.3839530e-06  1.4312100e-06  3.9983486e+03]
 [-1.9071158e-06 -9.5367432e-07  3.2920288e+03]
 [-1.9063009e-06 -2.3830216e-06 -1.2012737e+03]
 [ 5.8204819e-10  1.4302786e-06 -4.8412139e+03]
 [-1.6684644e-06 -2.6226044e-06  6.3846865e+03]
 [ 3.1001400e-06 -3.0989759e-06  2.3328838e+03]
 [ 1.6692793e-06  2.3841858e-07  1.5663926e+03]
 [-2.6221387e-06 -2.3795292e-07  7.4820908e+03]]

are these values normal?

**Comment by DeepanChakravarthiPadmanabhan** [comment]
Hey,
Can you please provide the missing details in the question like 'if the _____ is negative the output will always be 63, if positive it will be 64, so can you provide me with a solution to this.' ?

Next, on seeing your output, I suspect the model has not been trained properly, x and y values are very small and clumped together. I would suggest training with more weightage on the separation loss so that the keypoints are separated in x and y.

**Comment by Abdelrahman-Alkhodary** [comment]
Thanks for your reply, 
I will try to train it again just waiting for a more resourceful pc

for the missing part in the question, what i meant is in the above equation the term (min(max(x, -1), 1) always evaluate to 1 or -1 so the x will always evaluate to vw / 2 +/-1
